name: dypimr_alumni
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.1.0
  cupertino_icons: ^1.0.2

  #Google Sign In
  firebase_auth: ^3.3.5
  google_sign_in: ^5.0.3

  #Google Icon
  font_awesome_flutter: ^10.1.0

  email_validator: ^2.0.1

  #state Management
  provider: ^6.0.2

  flutter_screenutil: ^5.0.3

  flutter_local_notifications: ^9.7.0
  rxdart: ^0.27.5
  timezone: ^0.8.0

  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5

  google_fonts: ^2.2.0
  uuid: ^3.0.6
  image_picker: ^0.8.4+10
  file_picker: ^4.5.1
  firestore_search: ^0.1.9
  url_launcher: ^6.0.20
  firebase_messaging: ^12.0.1
  flutter_email_sender: ^5.1.0
  sendgrid_mailer: ^0.1.3

  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - lib/images/DPUlogo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
